[project]
name = "hello"
version = "0.1.0"
description = "An example Django app running in Docker."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "Django==5.1.6",
  "celery==5.4.0",
  "django-debug-toolbar==5.0.1",
  "gunicorn==23.0.0",
  "psycopg==3.2.5",
  "redis==5.2.1",
  "ruff==0.11.1",
  "setuptools==75.8.2",
  "whitenoise==6.9.0",
]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
extend-select = ["SIM"]
